var GAME_LEVELS = [
   ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xx                                 o                           o          xx  ",
   "  x                                                                    o     x  ",
   "  x                                xxxxx        p               xxx p        x  ",
   "  x                                                    xxxxx          xxx    x  ",
   "  x                                           xxxxx                          x  ",
   "  x      o  o  o               o  o                                          x  ",
   "  x                                      xxxxx                               x  ",
   "  x     xxxxxxxxx      p       xxxx        o                 o               x  ",
   "  x  @  x       x                                            y               x  ",
   "  xxxxxxx       xxxxxxxxxxxxx        xxxxxxxxxxx           xxxxx   xxxxxxxxxxx  ",
   "                            x!!!!!!!!x         x           x   x   x            ",
   "                            x!!!!!!!!x         x!!!!!!!!!!!x   x!!!x            ",
   "                            x!!!!!!!!x         x!!!!!!!!!!!x   x!!!x            ",
   "                            xxxxxxxxxx         xxxxxxxxxxxxx   xxxxx            ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                               xxxxxxv                            ",
   "                                                                              x                                   ",
   "                                                                             x  o o o                             ",
   "                                                                             x   o o                              ",
   "                                                                             !x                                   ",
   "                                                                             !!xxxxxx! o                          ",
   "                                                                             !!!!!!!!!                            ",
   "                                                                             |        xxx                         ",
   "                                                                                        p y                       ",
   "                                                                                    x!x!x!x     oo                ",
   "                                                                                    x!x!x!x        y              ",
   "                                                                                     v   v   xxx  xxx             ",
   "                                  y                                                           |    |    xxx  o    ",
   "                 oo               p                                                                           y p ",
   "                           o                                                                                  x   ",
   "               xx  xx  y                                                               p             o      x     ",
   "     @                     x                                                                              x       ",
   "xxxxxxxxxxxxxx         p          o                                                                 xxxx          ",
   "             x!!!!!!!!!x!!!!!!xxx x xxxxxx x x   o   xxxxxxxxxxx                          o  xxxx                 ",
   "             x!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!!x      x!!!!!!!!!!=                o                                ",
   "             x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!x  x y x!!!!!!!xxv          o           xxxx                        ",
   "             x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!xo   oxx!!!!!!xx                     y                              ",
   "             x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!xx   xx!!!!!!!!o          x  xxxxx   x                              ",
   "             x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       xxx                                             ",
   "             x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxo      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "             x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                     !!!!!!!!!!!!!                                            ",
   "                    o  oo  o                          |    |     |                                            ",
   "                    x!xxxx!x                                                                                  ",
   "                   x |v  v|vx                          o    o    o                                            ",
   "                  x          x                                            p                                   ",
   "                 x            x                      x   x    xx                                              ",
   "                x    o  o  o   x  y   xxxxxxx    x!!!!!!!!!x!!!!!!!x ooooooooooo                              ",
   "                 x   x  x  x      x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              ",
   "                  x                   o  o  o                                                                 ",
   "                   x           xxxxx                                                                          ",
   "                     x x x x x v v v x  x  x  x                                                               ",
   "                                     x!!!!!!!!x                                                               ",
   "                                     xxxxxxxxxx                                   o                           ",
   "                                                 x    o                          =x                           ",                                 
   "                                                                                                              ",
   "                                                    x=  x   p                  p p  p                         ",
   "                                                                                                              ",
   "                                                      o   x                                                   ",
   "                             y                                                                                ",
   "                       o     p                          x                           p     p                   ",
   "                  o        xxxxx  o  o                                                                        ",
   "             o        xxx           p      o   o      x         p       p                                     ",
   "                 xxx             x  x  x           y                                                          ",
   "         @  xxx                           x  x    xxxx                                                        ",
   "  !!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  "],
  ["                                                                                                              ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "  x         |             vv vv vv vv vv vv  |                        p                                       ",
   "  x                                             |                     p                                       ",
   "  x                                                |                  p                                       ",
   "  x         x                                         |               p                                       ",
   "  x    xxx!!x                                            |            p                                       ",
   "  xxxx      x                                               |         p                                       ",
   "  x!!!      x                                                  |      p                                       ",
   "  x  v x!x  x                                                     |   p                                       ",
   "  x         x                                                        |p                                       ",
   "  x=       xx     p                                                   p                                       ",
   "  x         x                                                         p                                       ",
   "  x   xxx   x                                                         p                                       ",
   "  x         x                                                         p                                       ",
   "  xxxx      x                                                         p                                       ",
   "  x    xxx  x                                                         p                                       ",
   "  x        yx            x  x  x  x  x  x  x                          p                                       ",
   "  x        xxy    y   y                     x=     =     =     =     =x                                       ",
   "  x      x!!xx xx xx xx!!!!!!!!!!!!!!!!!!!!!x                         x                                       ",
   "  x  @ x!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                        ox                                       ",
   "  xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
